# Generated by Django 3.1.6 on 2021-02-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice4',
            new_name='option4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
    ]
